### ISSUE TITLE
Option to add "name" property

### ISSUE THREAD

**Issue by niksy** [nickmessing/babel-plugin-jsx-vue-functional#1]
Adding `name` property could help in debugging your application. This could be defined as option for plugin so it isn’t active by default.

What do you think?

**Comment by nickmessing** [comment]
Hmm, sounds good, do you want to give it a try or should I?

**Comment by nickmessing** [comment]
Maybe instead of that we can just use NODE_ENV so developers don't have to configure anything?

**Comment by niksy** [comment]
If you’re not in a hurry, I can give it a shot when I get time.

As for `NODE_ENV`, do you mean injecting `process.env.NODE_ENV` in form of `name: process.env.NODE_ENV && 'componentName'` or testing if it’s already set and then adding component name via this plugin?

**Comment by nickmessing** [comment]
@niksy, I mean in `objectExpression` that is exported to add `name` property only if `process.env.NODE_ENV === 'development'`

So:
```jsx
export const a = ({ props, listeners }) => <div onClick={listeners.click}>{props.msg}</div>
```

Transpiled with `NODE_ENV === 'development'`:
```jsx
export const a = {
  functional: true,
  name: 'a',
  render: (h, { props, listeners }) => <div onClick={listeners.click}>{props.msg}</div>
};
```

And without:
```jsx
export const a = {
  functional: true,
  render: (h, { props, listeners }) => <div onClick={listeners.click}>{props.msg}</div>
};
```

So we don't have `name` filed in production, I can't think of any reason to have it there, for functional components.

**Comment by niksy** [comment]
@nickmessing done!
