### ISSUE TITLE
How to use, newbie at functional components

### ISSUE THREAD

**Issue by paulm17** [nickmessing/babel-plugin-jsx-vue-functional#11]
I'm a total newbie at jsx functional components.  Hopefully you can provide an example of how to use them.  I don't understand what's on the readme and articles such as:

    https://alligator.io/vuejs/render-functional-components/

Aren't that helpful for a beginner like me.  I'm able to understand "babel-plugin-transform-vue-jsx" ok, but this topic eludes me right now.

From my example I keep on getting "draggableItems is not a function".  Although I can console.log it and I see the object just fine.  But I'm struggling to make it work.

Here's a quick example:

	export default function(h, index, itemsLength) {
		const draggableItems = (index, itemsLength) => {
			let dragControls = [];
			let draggableClass = "...";

			if (index == 0) {
				draggableClass += " right";
				dragControls.push(draggableClass);
			} else if (index < (itemsLength - 1)) {
				draggableClass += " left";
				dragControls.push(draggableClass);
			} else {
				draggableClass += " right";
				dragControls.push(draggableClass);

				draggableClass += " left";
				dragControls.push(draggableClass);
			}		

			const items = dragControls.map((draggableClass) => {
				return <div class={draggableClass}>
					[ ... stuf here ...]
				</div>
			});

			return { items }		
		}	

		return draggableItems(index, itemsLength);
	}

**Comment by paulm17** [comment]
I found if I move 

    return <div class={draggableClass}>
        [ ... stuf here ...]
    </div>

into it's own function outside of the template.

	function draggableControl(h, draggableClass) {
	    return <div class={draggableClass}>
			 [ ... stuf here ...]
		</div>
	}

    export default function(h, index, itemsLength) {
        ...

and then do:

	const items = dragControls.map((draggableClass) => {
		return draggableControl(h, draggableClass)
	});

Seems to work fine.

Now if I try to make it a functional component: 

    const draggableControl = (draggableClass) => {

I get:

    draggableControl is not a function

Thanks!

**Comment by nickmessing** [comment]
This plugin is designed only for primitive functional components like:
```js
export const FunctionalButton = ({ data, children }) =>
  <button {...data}>
    {children}
  </button >
```
So, basically it should be:
1. Uppercase
2. have no body (no `{}` after `=>`)
3. It should just return JSX construction
