### ISSUE TITLE
Transpiling non-exported functions?

### ISSUE THREAD

**Issue by niksy** [nickmessing/babel-plugin-jsx-vue-functional#2]
Documentation says:

> This plugin will transform all named exported arrow functions that contain JSX.

What about non-exported functions, e.g. small components defined in same file as larger component? Do you think this makes sense for transpiling, or transpiler can encounter problems with false positives?

**Comment by nickmessing** [comment]
@niksy, I think we can do that for:
```jsx
const a = ({ props, listeners }) => <div onClick={listeners.click}>{props.msg}</div>
```
with the condition of:
1. Defined as `const`
2. Is arrow function
3. Contains JSX

Sounds like a good idea to me

**Comment by nickmessing** [comment]
@niksy, done and bumped version to 2.0.0 since it's not reverse-compatible.
